version: 2
jobs:
  deploy-staging:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/django-demo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ea:ec:05:37:d9:7a:81:83:24:64:93:c6:96:a6:f9:24"      
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Archive content of git repo without git files
          command: git archive -o django-demo.zip --format=zip HEAD
      - run:
          name: Create app folder
          command: mkdir django-demo
      - run:
          name: Unzip app package
          command: cd django-demo && unzip ../django-demo.zip
      - run:
          name: Remove unimportant stuff
          command: cd django-demo && rm -rf .circleci && rm .gitignore
      - run:
          name: Fix host authenticity for 18.233.46.10
          command: |
            ssh-keyscan 52.0.217.29 >> ~/.ssh/known_hosts
            echo "Host *" >> ~/.ssh/config
            echo "    User ubuntu" >> ~/.ssh/config
            echo "    ForwardAgent Yes" >> ~/.ssh/config
      - run:
          name: Deploy to EC2
          command: scp -r django-demo ubuntu@52.0.217.29:~/circleci

      - run:
          name: test command
          command: ssh ubuntu@52.0.217.29 /home/ubuntu/test.sh
workflows:
  version: 2
  build:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: master        